### ISSUE TITLE
ログインページから登録ページに移動する時にエラーが残る

### ISSUE THREAD

**Issue by Dimda** [oic-ogma/plant-watcher-app#31]
## 説明
**レビューに必要人数：1人**
**ブランチ名：`bug/31-error-message-stays-after-moving-page`**

ログインページから登録ページに移動する時にエラーが残っている。

## タスク
- [x] ページ移動とステートをリセットするアクションクリエーターを作成

**Comment by youmjww** [comment]
説明の、
`今現在は画像認証などは必要なく、写真が取れるだけでよい。` 
これは、誤植？
あと、レビューしてよければ、レビュー待ちのタグを付けてほしいです。

**Comment by Dimda** [comment]
@youmjww 誤植。
