### ISSUE TITLE
全体的リファクタリング

### ISSUE THREAD

**Issue by Dimda** [oic-ogma/plant-watcher-app#33]
## 説明
**レビューに必要人数：** 1人
**ブランチ名：**`refactoring/33-general-refactoring`

## タスク
- [x] `LoginForm.test.js`から`user`削除
- [x] `AuthActions.test.js`から`user`削除
- [x] `RegistrationForm.test.js`から`user`削除
- [x] `AuthReducer.test.js`から`user`削除
- [x] `AuthActions.js`から`user`削除
- [x] `AuthReducer.js`から`user`削除
- [x] `on...Changed` がコンポーネント内で書いてあるところを削除、直接propsから渡されたaction creatorを使う
- [x] `saveArticle`でキーを別に作成するではなく、直接pushする

**Comment by youmjww** [comment]
完了したのでCloseします。
